import { Country } from "./utils";

// Create a constant array and derive the type from it
export const CONTINENTS = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
] as const;

export const COUNTRIES: Country[] = [
  // Africa
  { code: "DZ", name: "Algeria", emoji: "🇩🇿", continent: "Africa" },
  { code: "AO", name: "Angola", emoji: "🇦🇴", continent: "Africa" },
  { code: "BJ", name: "Benin", emoji: "🇧🇯", continent: "Africa" },
  { code: "BW", name: "Botswana", emoji: "🇧🇼", continent: "Africa" },
  { code: "BF", name: "Burkina Faso", emoji: "🇧🇫", continent: "Africa" },
  { code: "BI", name: "Burundi", emoji: "🇧🇮", continent: "Africa" },
  { code: "CM", name: "Cameroon", emoji: "🇨🇲", continent: "Africa" },
  { code: "CV", name: "Cape Verde", emoji: "🇨🇻", continent: "Africa" },
  {
    code: "CF",
    name: "Central African Republic",
    emoji: "🇨🇫",
    continent: "Africa",
  },
  { code: "TD", name: "Chad", emoji: "🇹🇩", continent: "Africa" },
  { code: "KM", name: "Comoros", emoji: "🇰🇲", continent: "Africa" },
  { code: "CG", name: "Congo", emoji: "🇨🇬", continent: "Africa" },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    emoji: "🇨🇩",
    continent: "Africa",
  },
  { code: "CI", name: "Ivory Coast", emoji: "🇨🇮", continent: "Africa" },
  { code: "DJ", name: "Djibouti", emoji: "🇩🇯", continent: "Africa" },
  { code: "EG", name: "Egypt", emoji: "🇪🇬", continent: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", emoji: "🇬🇶", continent: "Africa" },
  { code: "ER", name: "Eritrea", emoji: "🇪🇷", continent: "Africa" },
  { code: "ET", name: "Ethiopia", emoji: "🇪🇹", continent: "Africa" },
  { code: "GA", name: "Gabon", emoji: "🇬🇦", continent: "Africa" },
  { code: "GM", name: "Gambia", emoji: "🇬🇲", continent: "Africa" },
  { code: "GH", name: "Ghana", emoji: "🇬🇭", continent: "Africa" },
  { code: "GN", name: "Guinea", emoji: "🇬🇳", continent: "Africa" },
  { code: "GW", name: "Guinea-Bissau", emoji: "🇬🇼", continent: "Africa" },
  { code: "KE", name: "Kenya", emoji: "🇰🇪", continent: "Africa" },
  { code: "LS", name: "Lesotho", emoji: "🇱🇸", continent: "Africa" },
  { code: "LR", name: "Liberia", emoji: "🇱🇷", continent: "Africa" },
  { code: "LY", name: "Libya", emoji: "🇱🇾", continent: "Africa" },
  { code: "MG", name: "Madagascar", emoji: "🇲🇬", continent: "Africa" },
  { code: "MW", name: "Malawi", emoji: "🇲🇼", continent: "Africa" },
  { code: "ML", name: "Mali", emoji: "🇲🇱", continent: "Africa" },
  { code: "MR", name: "Mauritania", emoji: "🇲🇷", continent: "Africa" },
  { code: "MU", name: "Mauritius", emoji: "🇲🇺", continent: "Africa" },
  { code: "MA", name: "Morocco", emoji: "🇲🇦", continent: "Africa" },
  { code: "MZ", name: "Mozambique", emoji: "🇲🇿", continent: "Africa" },
  { code: "NA", name: "Namibia", emoji: "🇳🇦", continent: "Africa" },
  { code: "NE", name: "Niger", emoji: "🇳🇪", continent: "Africa" },
  { code: "NG", name: "Nigeria", emoji: "🇳🇬", continent: "Africa" },
  { code: "RW", name: "Rwanda", emoji: "🇷🇼", continent: "Africa" },
  { code: "SN", name: "Senegal", emoji: "🇸🇳", continent: "Africa" },
  { code: "SC", name: "Seychelles", emoji: "🇸🇨", continent: "Africa" },
  { code: "SL", name: "Sierra Leone", emoji: "🇸🇱", continent: "Africa" },
  { code: "SO", name: "Somalia", emoji: "🇸🇴", continent: "Africa" },
  { code: "ZA", name: "South Africa", emoji: "🇿🇦", continent: "Africa" },
  { code: "SS", name: "South Sudan", emoji: "🇸🇸", continent: "Africa" },
  { code: "SD", name: "Sudan", emoji: "🇸🇩", continent: "Africa" },
  { code: "SZ", name: "Eswatini", emoji: "🇸🇿", continent: "Africa" },
  { code: "TZ", name: "Tanzania", emoji: "🇹🇿", continent: "Africa" },
  { code: "TG", name: "Togo", emoji: "🇹🇬", continent: "Africa" },
  { code: "TN", name: "Tunisia", emoji: "🇹🇳", continent: "Africa" },
  { code: "UG", name: "Uganda", emoji: "🇺🇬", continent: "Africa" },
  { code: "EH", name: "Western Sahara", emoji: "🇪🇭", continent: "Africa" },
  { code: "ZM", name: "Zambia", emoji: "🇿🇲", continent: "Africa" },
  { code: "ZW", name: "Zimbabwe", emoji: "🇿🇼", continent: "Africa" },

  // Asia
  { code: "AF", name: "Afghanistan", emoji: "🇦🇫", continent: "Asia" },
  { code: "AM", name: "Armenia", emoji: "🇦🇲", continent: "Asia" },
  { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿", continent: "Asia" },
  { code: "BH", name: "Bahrain", emoji: "🇧🇭", continent: "Asia" },
  { code: "BD", name: "Bangladesh", emoji: "🇧🇩", continent: "Asia" },
  { code: "BT", name: "Bhutan", emoji: "🇧🇹", continent: "Asia" },
  { code: "BN", name: "Brunei", emoji: "🇧🇳", continent: "Asia" },
  { code: "KH", name: "Cambodia", emoji: "🇰🇭", continent: "Asia" },
  { code: "CN", name: "China", emoji: "🇨🇳", continent: "Asia" },
  { code: "CY", name: "Cyprus", emoji: "🇨🇾", continent: "Asia" },
  { code: "GE", name: "Georgia", emoji: "🇬🇪", continent: "Asia" },
  { code: "IN", name: "India", emoji: "🇮🇳", continent: "Asia" },
  { code: "ID", name: "Indonesia", emoji: "🇮🇩", continent: "Asia" },
  { code: "IR", name: "Iran", emoji: "🇮🇷", continent: "Asia" },
  { code: "IQ", name: "Iraq", emoji: "🇮🇶", continent: "Asia" },
  { code: "IL", name: "Israel", emoji: "🇮🇱", continent: "Asia" },
  { code: "JP", name: "Japan", emoji: "🇯🇵", continent: "Asia" },
  { code: "JO", name: "Jordan", emoji: "🇯🇴", continent: "Asia" },
  { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿", continent: "Asia" },
  { code: "KP", name: "North Korea", emoji: "🇰🇵", continent: "Asia" },
  { code: "KR", name: "South Korea", emoji: "🇰🇷", continent: "Asia" },
  { code: "KW", name: "Kuwait", emoji: "🇰🇼", continent: "Asia" },
  { code: "KG", name: "Kyrgyzstan", emoji: "🇰🇬", continent: "Asia" },
  { code: "LA", name: "Laos", emoji: "🇱🇦", continent: "Asia" },
  { code: "LB", name: "Lebanon", emoji: "🇱🇧", continent: "Asia" },
  { code: "MY", name: "Malaysia", emoji: "🇲🇾", continent: "Asia" },
  { code: "MV", name: "Maldives", emoji: "🇲🇻", continent: "Asia" },
  { code: "MN", name: "Mongolia", emoji: "🇲🇳", continent: "Asia" },
  { code: "MM", name: "Myanmar", emoji: "🇲🇲", continent: "Asia" },
  { code: "NP", name: "Nepal", emoji: "🇳🇵", continent: "Asia" },
  { code: "OM", name: "Oman", emoji: "🇴🇲", continent: "Asia" },
  { code: "PK", name: "Pakistan", emoji: "🇵🇰", continent: "Asia" },
  { code: "PS", name: "Palestine", emoji: "🇵🇸", continent: "Asia" },
  { code: "PH", name: "Philippines", emoji: "🇵🇭", continent: "Asia" },
  { code: "QA", name: "Qatar", emoji: "🇶🇦", continent: "Asia" },
  { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦", continent: "Asia" },
  { code: "SG", name: "Singapore", emoji: "🇸🇬", continent: "Asia" },
  { code: "LK", name: "Sri Lanka", emoji: "🇱🇰", continent: "Asia" },
  { code: "SY", name: "Syria", emoji: "🇸🇾", continent: "Asia" },
  { code: "TW", name: "Taiwan", emoji: "🇹🇼", continent: "Asia" },
  { code: "TJ", name: "Tajikistan", emoji: "🇹🇯", continent: "Asia" },
  { code: "TH", name: "Thailand", emoji: "🇹🇭", continent: "Asia" },
  { code: "TL", name: "Timor-Leste", emoji: "🇹🇱", continent: "Asia" },
  { code: "TR", name: "Turkey", emoji: "🇹🇷", continent: "Asia" },
  { code: "TM", name: "Turkmenistan", emoji: "🇹🇲", continent: "Asia" },
  { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪", continent: "Asia" },
  { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿", continent: "Asia" },
  { code: "VN", name: "Vietnam", emoji: "🇻🇳", continent: "Asia" },
  { code: "YE", name: "Yemen", emoji: "🇾🇪", continent: "Asia" },

  // Europe
  { code: "AL", name: "Albania", emoji: "🇦🇱", continent: "Europe" },
  { code: "AD", name: "Andorra", emoji: "🇦🇩", continent: "Europe" },
  { code: "AT", name: "Austria", emoji: "🇦🇹", continent: "Europe" },
  { code: "BY", name: "Belarus", emoji: "🇧🇾", continent: "Europe" },
  { code: "BE", name: "Belgium", emoji: "🇧🇪", continent: "Europe" },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    emoji: "🇧🇦",
    continent: "Europe",
  },
  { code: "BG", name: "Bulgaria", emoji: "🇧🇬", continent: "Europe" },
  { code: "HR", name: "Croatia", emoji: "🇭🇷", continent: "Europe" },
  { code: "CY", name: "Cyprus", emoji: "🇨🇾", continent: "Europe" },
  { code: "CZ", name: "Czech Republic", emoji: "🇨🇿", continent: "Europe" },
  { code: "DK", name: "Denmark", emoji: "🇩🇰", continent: "Europe" },
  { code: "EE", name: "Estonia", emoji: "🇪🇪", continent: "Europe" },
  { code: "FO", name: "Faroe Islands", emoji: "🇫🇴", continent: "Europe" },
  { code: "FI", name: "Finland", emoji: "🇫🇮", continent: "Europe" },
  { code: "FR", name: "France", emoji: "🇫🇷", continent: "Europe" },
  { code: "DE", name: "Germany", emoji: "🇩🇪", continent: "Europe" },
  { code: "GI", name: "Gibraltar", emoji: "🇬🇮", continent: "Europe" },
  { code: "GR", name: "Greece", emoji: "🇬🇷", continent: "Europe" },
  { code: "GG", name: "Guernsey", emoji: "🇬🇬", continent: "Europe" },
  { code: "HU", name: "Hungary", emoji: "🇭🇺", continent: "Europe" },
  { code: "IS", name: "Iceland", emoji: "🇮🇸", continent: "Europe" },
  { code: "IE", name: "Ireland", emoji: "🇮🇪", continent: "Europe" },
  { code: "IM", name: "Isle of Man", emoji: "🇮🇲", continent: "Europe" },
  { code: "IT", name: "Italy", emoji: "🇮🇹", continent: "Europe" },
  { code: "JE", name: "Jersey", emoji: "🇯🇪", continent: "Europe" },
  { code: "LV", name: "Latvia", emoji: "🇱🇻", continent: "Europe" },
  { code: "LI", name: "Liechtenstein", emoji: "🇱🇮", continent: "Europe" },
  { code: "LT", name: "Lithuania", emoji: "🇱🇹", continent: "Europe" },
  { code: "LU", name: "Luxembourg", emoji: "🇱🇺", continent: "Europe" },
  { code: "MT", name: "Malta", emoji: "🇲🇹", continent: "Europe" },
  { code: "MD", name: "Moldova", emoji: "🇲🇩", continent: "Europe" },
  { code: "MC", name: "Monaco", emoji: "🇲🇨", continent: "Europe" },
  { code: "ME", name: "Montenegro", emoji: "🇲🇪", continent: "Europe" },
  { code: "NL", name: "Netherlands", emoji: "🇳🇱", continent: "Europe" },
  { code: "NO", name: "Norway", emoji: "🇳🇴", continent: "Europe" },
  { code: "PL", name: "Poland", emoji: "🇵🇱", continent: "Europe" },
  { code: "PT", name: "Portugal", emoji: "🇵🇹", continent: "Europe" },
  { code: "RO", name: "Romania", emoji: "🇷🇴", continent: "Europe" },
  { code: "RU", name: "Russia", emoji: "🇷🇺", continent: "Europe" },
  { code: "SM", name: "San Marino", emoji: "🇸🇲", continent: "Europe" },
  { code: "RS", name: "Serbia", emoji: "🇷🇸", continent: "Europe" },
  { code: "SK", name: "Slovakia", emoji: "🇸🇰", continent: "Europe" },
  { code: "SI", name: "Slovenia", emoji: "🇸🇮", continent: "Europe" },
  { code: "ES", name: "Spain", emoji: "🇪🇸", continent: "Europe" },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    emoji: "🇸🇯",
    continent: "Europe",
  },
  { code: "SE", name: "Sweden", emoji: "🇸🇪", continent: "Europe" },
  { code: "CH", name: "Switzerland", emoji: "🇨🇭", continent: "Europe" },
  { code: "UA", name: "Ukraine", emoji: "🇺🇦", continent: "Europe" },
  { code: "GB", name: "United Kingdom", emoji: "🇬🇧", continent: "Europe" },
  { code: "VA", name: "Vatican City", emoji: "🇻🇦", continent: "Europe" },

  // North America
  {
    code: "AG",
    name: "Antigua and Barbuda",
    emoji: "🇦🇬",
    continent: "North America",
  },
  { code: "BS", name: "Bahamas", emoji: "🇧🇸", continent: "North America" },
  { code: "BB", name: "Barbados", emoji: "🇧🇧", continent: "North America" },
  { code: "BZ", name: "Belize", emoji: "🇧🇿", continent: "North America" },
  { code: "CA", name: "Canada", emoji: "🇨🇦", continent: "North America" },
  { code: "CR", name: "Costa Rica", emoji: "🇨🇷", continent: "North America" },
  { code: "CU", name: "Cuba", emoji: "🇨🇺", continent: "North America" },
  { code: "DM", name: "Dominica", emoji: "🇩🇲", continent: "North America" },
  {
    code: "DO",
    name: "Dominican Republic",
    emoji: "🇩🇴",
    continent: "North America",
  },
  { code: "SV", name: "El Salvador", emoji: "🇸🇻", continent: "North America" },
  { code: "GD", name: "Grenada", emoji: "🇬🇩", continent: "North America" },
  { code: "GT", name: "Guatemala", emoji: "🇬🇹", continent: "North America" },
  { code: "HT", name: "Haiti", emoji: "🇭🇹", continent: "North America" },
  { code: "HN", name: "Honduras", emoji: "🇭🇳", continent: "North America" },
  { code: "JM", name: "Jamaica", emoji: "🇯🇲", continent: "North America" },
  { code: "MX", name: "Mexico", emoji: "🇲🇽", continent: "North America" },
  { code: "NI", name: "Nicaragua", emoji: "🇳🇮", continent: "North America" },
  { code: "PA", name: "Panama", emoji: "🇵🇦", continent: "North America" },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    emoji: "🇰🇳",
    continent: "North America",
  },
  { code: "LC", name: "Saint Lucia", emoji: "🇱🇨", continent: "North America" },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    emoji: "🇻🇨",
    continent: "North America",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    emoji: "🇹🇹",
    continent: "North America",
  },
  {
    code: "US",
    name: "United States",
    emoji: "🇺🇸",
    continent: "North America",
  },

  // South America
  { code: "AR", name: "Argentina", emoji: "🇦🇷", continent: "South America" },
  { code: "BO", name: "Bolivia", emoji: "🇧🇴", continent: "South America" },
  { code: "BR", name: "Brazil", emoji: "🇧🇷", continent: "South America" },
  { code: "CL", name: "Chile", emoji: "🇨🇱", continent: "South America" },
  { code: "CO", name: "Colombia", emoji: "🇨🇴", continent: "South America" },
  { code: "EC", name: "Ecuador", emoji: "🇪🇨", continent: "South America" },
  { code: "GY", name: "Guyana", emoji: "🇬🇾", continent: "South America" },
  { code: "PY", name: "Paraguay", emoji: "🇵🇾", continent: "South America" },
  { code: "PE", name: "Peru", emoji: "🇵🇪", continent: "South America" },
  { code: "SR", name: "Suriname", emoji: "🇸🇷", continent: "South America" },
  { code: "UY", name: "Uruguay", emoji: "🇺🇾", continent: "South America" },
  { code: "VE", name: "Venezuela", emoji: "🇻🇪", continent: "South America" },

  // Oceania
  { code: "AS", name: "American Samoa", emoji: "🇦🇸", continent: "Oceania" },
  { code: "AU", name: "Australia", emoji: "🇦🇺", continent: "Oceania" },
  { code: "CK", name: "Cook Islands", emoji: "🇨🇰", continent: "Oceania" },
  { code: "FJ", name: "Fiji", emoji: "🇫🇯", continent: "Oceania" },
  { code: "PF", name: "French Polynesia", emoji: "🇵🇫", continent: "Oceania" },
  { code: "GU", name: "Guam", emoji: "🇬🇺", continent: "Oceania" },
  { code: "KI", name: "Kiribati", emoji: "🇰🇮", continent: "Oceania" },
  { code: "MH", name: "Marshall Islands", emoji: "🇲🇭", continent: "Oceania" },
  { code: "FM", name: "Micronesia", emoji: "🇫🇲", continent: "Oceania" },
  { code: "NR", name: "Nauru", emoji: "🇳🇷", continent: "Oceania" },
  { code: "NC", name: "New Caledonia", emoji: "🇳🇨", continent: "Oceania" },
  { code: "NZ", name: "New Zealand", emoji: "🇳🇿", continent: "Oceania" },
  { code: "NU", name: "Niue", emoji: "🇳🇺", continent: "Oceania" },
  { code: "NF", name: "Norfolk Island", emoji: "🇳🇫", continent: "Oceania" },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
    continent: "Oceania",
  },
  { code: "PW", name: "Palau", emoji: "🇵🇼", continent: "Oceania" },
  { code: "PG", name: "Papua New Guinea", emoji: "🇵🇬", continent: "Oceania" },
  { code: "PN", name: "Pitcairn Islands", emoji: "🇵🇳", continent: "Oceania" },
  { code: "WS", name: "Samoa", emoji: "🇼🇸", continent: "Oceania" },
  { code: "SB", name: "Solomon Islands", emoji: "🇸🇧", continent: "Oceania" },
  { code: "TK", name: "Tokelau", emoji: "🇹🇰", continent: "Oceania" },
  { code: "TO", name: "Tonga", emoji: "🇹🇴", continent: "Oceania" },
  { code: "TV", name: "Tuvalu", emoji: "🇹🇻", continent: "Oceania" },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    emoji: "🇺🇲",
    continent: "Oceania",
  },
  { code: "VU", name: "Vanuatu", emoji: "🇻🇺", continent: "Oceania" },
  { code: "WF", name: "Wallis and Futuna", emoji: "🇼🇫", continent: "Oceania" },
];
